### ISSUE TITLE
3.5.4直接运行出错,3.53就没问题,是哪需要修改设置?

### ISSUE THREAD

**Issue by cnrip** [SeaHOH/GotoX#134] opened 2019-10-09 10:03 UTC
Traceback (most recent call last):
  File "D:\GotoX-3.5.4-cp36-win_amd64\start.py", line 9, in <module>
    from local import proxy
  File "D:\GotoX-3.5.4-cp36-win_amd64\local\proxy.py", line 90, in <module>
    from .ProxyServer import network_test, start_proxyserver
  File "D:\GotoX-3.5.4-cp36-win_amd64\local\ProxyServer.py", line 129, in <module>
    from .ProxyHandler import AutoProxyHandler, GAEProxyHandler
  File "D:\GotoX-3.5.4-cp36-win_amd64\local\ProxyHandler.py", line 33, in <module>
    from .RangeFetch import RangeFetchs
  File "D:\GotoX-3.5.4-cp36-win_amd64\local\RangeFetch.py", line 13, in <module>
    from .GAEFetch import get_appid, mark_badappid, gae_urlfetch
  File "D:\GotoX-3.5.4-cp36-win_amd64\local\GAEFetch.py", line 38, in <module>
    LimitGAE.init()
  File "D:\GotoX-3.5.4-cp36-win_amd64\local\common\util.py", line 307, in init
    cls._limiter = cls._limiterFactory()
  File "D:\GotoX-3.5.4-cp36-win_amd64\local\common\util.py", line 302, in _limiterFactory
    return Limiter(cls.maxsize)
  File "D:\GotoX-3.5.4-cp36-win_amd64\local\common\util.py", line 225, in __init__
    raise ValueError('The maxsize can not be less than 1.')
ValueError: The maxsize can not be less than 1.

**Comment by SeaHOH** [comment] 2019-10-09 10:07
Duplicate of #123 请更新到主分支

**Closed by SeaHOH** 2019-10-09 10:07 UTC
